blog/urls.py
# coding: utf-8
from django.conf.urls import url
from . import views as blog_view

app_name = 'blog'


urlpatterns = [
    url(r'^$', blog_view.index, name='index'),            # 首页
    url(r'^about/$', blog_view.about, name='about'),
    url(r'^archive/$', blog_view.archive, name='archive'),
    url(r'^link/$', blog_view.link, name='link'),
    url(r'^comment$', blog_view.comment, name='comment'),
    url(r'^blog/(?P<pk>\d+)/$', blog_view.blog, name='article'),
    url(r'^getcomment/$', blog_view.get_comment, name='getcomment'),
    url(r'^detail/(?P<pk>\d+)/$', blog_view.detail, name='detail'),
    url(r'^detail/(?P<pk>\d+)$', blog_view.detail, name='detail'),
    url(r'^search/$', blog_view.search, name='search'),
    url(r'^tag/(?P<name>.*?)/$', blog_view.tag, name='tag'),
]

mydjango2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from mysite import views as mysite_view
from login import views as login_view

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', mysite_view.index, name='index'),            # 首页
    url(r'^index/$', login_view.login_log, name='index'),   # 首页
    url(r'^blog/', include('blog.urls')),                   # 博客
    url(r'^vote/', include('vote.urls')),                   # 投票
    url(r'^assets/', include('assets.urls')),
]

vote/urls.py
from django.conf.urls import url
from . import views

app_name = 'vote'

urlpatterns = [
    # ex: /vote/
    url(r'^$', views.index, name='index'),
    # ex: /vote/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /vote/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /vote/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

vote/models.py
import datetime
from django.db import models
import django.utils.timezone as timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=300, verbose_name='问题')
    # pub_date = models.DateTimeField(default=timezone.now, verbose_name='发布日期')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='发布日期')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    class Meta:
        verbose_name = '问题'
        verbose_name_plural = verbose_name


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200, verbose_name='选项')
    votes = models.IntegerField(default=0, verbose_name='选择数')

    def __str__(self):
        return self.choice_text

    class Meta:
        verbose_name = '选项'
        verbose_name_plural = verbose_name

vote/views.py
from django.template import loader
from django.shortcuts import render
from django.shortcuts import reverse
from django.shortcuts import HttpResponse
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from .models import Question
from .models import Choice

# Create your views here.


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('vote/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'vote/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'vote/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'vote/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('vote:results', args=(question.id,)))

templates/vote/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'vote:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="点击投票" />
</form>

templates/vote/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vote投票</title>
</head>
<body>
<h2>请点击进行选择：</h2>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="/vote/{{ question.id }}/">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

templates/vote/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'vote:detail' question.id %}">再投一次？</a>
<br>
<a href="{% url 'vote:index' %}">返回投票首页</a>