blog/urls.py
# coding: utf-8
from django.conf.urls import url
from . import views as blog_view

app_name = 'blog'


urlpatterns = [
    url(r'^$', blog_view.index, name='index'),            # 首页
    url(r'^about/$', blog_view.about, name='about'),
    url(r'^archive/$', blog_view.archive, name='archive'),
    url(r'^link/$', blog_view.link, name='link'),
    url(r'^comment$', blog_view.comment, name='comment'),
    url(r'^blog/(?P<pk>\d+)/$', blog_view.blog, name='article'),
    url(r'^getcomment/$', blog_view.get_comment, name='getcomment'),
    url(r'^detail/(?P<pk>\d+)/$', blog_view.detail, name='detail'),
    url(r'^detail/(?P<pk>\d+)$', blog_view.detail, name='detail'),
    url(r'^search/$', blog_view.search, name='search'),
    url(r'^tag/(?P<name>.*?)/$', blog_view.tag, name='tag'),
]

mydjango2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from mysite import views as mysite_view
from login import views as login_view

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', mysite_view.index, name='index'),            # 首页
    url(r'^index/$', login_view.login_log, name='index'),   # 首页
    url(r'^blog/', include('blog.urls')),                   # 博客
    url(r'^vote/', include('vote.urls')),                   # 投票
    url(r'^assets/', include('assets.urls')),
]

blog/models.py
# coding: utf-8

from django.db import models
from django.conf import settings

# Create your models here.


class Tag(models.Model):
    tag_name = models.CharField(max_length=10, verbose_name='标签名')

    def __str__(self):
        return self.tag_name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name='标题')
    category = models.ForeignKey('Category', verbose_name='分类', on_delete=models.CASCADE)
    date_time = models.DateField(auto_now_add=True, verbose_name='发布日期')
    content = models.TextField(blank=True, null=True, verbose_name='内容')
    digest = models.TextField(blank=True, null=True, verbose_name='摘要')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)
    view = models.BigIntegerField(default=0, verbose_name='浏览数')
    comment = models.BigIntegerField(default=0, verbose_name='评论数')
    picture = models.CharField(max_length=200, verbose_name='标题图片地址')
    tag = models.ManyToManyField(Tag, '标签')

    def __str__(self):
        return self.title

    def sourceUrl(self):
        source_url = settings.HOST + '/blog/detail/{id}'.format(id=self.pk)
        return source_url  # 给网易云跟帖使用

    def viewed(self):
        """
        增加阅读数
        :return:
        """
        self.view += 1
        self.save(update_fields=['view'])

    def commenced(self):
        """
        增加评论数
        :return:
        """
        self.comment += 1
        self.save(update_fields=['comment'])

    class Meta:  # 按时间降序
        ordering = ['-date_time']
        verbose_name = '文章'
        verbose_name_plural = verbose_name


class Category(models.Model):
    name = models.CharField(max_length=30, verbose_name='类别')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    last_mod_time = models.DateTimeField(auto_now=True, verbose_name='最近修改时间')

    class Meta:
        ordering = ['name']
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Comment(models.Model):
    title = models.CharField(max_length=100, verbose_name='标题')
    source_id = models.CharField(max_length=25, verbose_name='文章id或source名称')
    create_time = models.DateTimeField(auto_now=True, verbose_name='评论时间')
    user_name = models.CharField(max_length=25, verbose_name='评论用户')
    url = models.CharField(max_length=100, verbose_name='链接')
    comment = models.CharField(max_length=500, verbose_name='评论内容')

    def __str__(self):
        return self.comment

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

blog/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from blog.models import Article, Category, Comment


def index(request):
    """
    博客首页
    :param request:
    :return:
    """
    article_list = Article.objects.all().order_by('-date_time')[0:5]
    return render(request, 'blog/index.html', {"article_list": article_list,
                                               "source_id": "index"})


def blog(request, pk):
    """
    博客列表页面
    :param request:
    :param pk:
    :return:
    """
    pk = int(pk)
    if pk:
        category_object = get_object_or_404(Category, pk=pk)
        category = category_object.name
        article_list = Article.objects.filter(category_id=pk)
    else:
        # pk为0时表示全部
        article_list = Article.objects.all()  # 获取全部文章
        category = u''
    return render(request, 'blog/articles.html',
                  {"article_list": article_list, "category": category, }
                  )


def about(request):
    return render(request, 'blog/about.html')


def archive(request):
    article_list = Article.objects.order_by('-date_time')
    return render(request, 'blog/archive.html', {"article_list": article_list})


def link(request):
    return render(request, 'blog/link.html')


def comment(request):
    return render(request, 'blog/comment_board.html', {"source_id": "message"})


@csrf_exempt
def get_comment(request):
    """
    接收畅言的评论回推， post方式回推
    :param request:
    :return:
    """
    arg = request.POST
    data = arg.get('data')
    data = json.loads(data)
    title = data.get('title')
    url = data.get('url')
    source_id = data.get('sourceid')
    if source_id not in ['message']:
        article = Article.objects.get(pk=source_id)
        article.commenced()
    comments = data.get('comments')[0]
    content = comments.get('content')
    user = comments.get('user').get('nickname')
    Comment(title=title, source_id=source_id, user_name=user, url=url, comment=content).save()
    return JsonResponse({"status": "ok"})


def detail(request, pk):
    """
    博文详情
    :param request:
    :param pk:
    :return:
    """
    article = get_object_or_404(Article, pk=pk)
    article.viewed()
    return render(request, 'blog/detail.html', {"article": article,
                                                "source_id": article.id})


def search(request):
    """
    搜索
    :param request:
    :return:
    """
    key = request.GET['key']
    article_list = Article.objects.filter(title__icontains=key)
    return render(request, 'blog/search.html',
                  {"article_list": article_list, "key": key})


def tag(request, name):
    """
    标签
    :param request:
    :param name
    :return:
    """
    article_list = Article.objects.filter(tag__tag_name=name)
    return render(request, 'blog/tag.html', {"article_list": article_list,
                                             "tag": name})

templates/blog/articles.html
{% extends "blog/base.html" %}
{% load custom_filter %}

{% block title %}
    <title>博客列表 - 朱皮特</title>
{% endblock %}

{% block content %}
    {% paginate article_list 8 %}
    {% if article_list %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "blog:article" pk=0 %}"><i class="el-th-list"></i>{% if category %}列表{% else %} 全部 {% endif %} &nbsp;&nbsp;> &nbsp;&nbsp;</a>
            <span class="orange-text">{{ category }}</span>
            <span style="float:right;margin-right:10px;">共有文章:<a class="orange-text"> {{ count }} </a>篇</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.view > 500 %}id="tuijian"{% elif article.view > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ article.picture }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "blog:detail" pk=article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.date_time }} 发表 "><i class="el-time"></i> {{ article.date_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>
                            <li><a href="#" title="已有 {{ article.comment }} 条评论"><i class="el-comment"></i>{{ article.comment }}</a>
                            </li>
                            <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "blog:article" pk=article.category_id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>

                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}">尾页</a></li>
            </ul>
        </div>

    </section>
    {% else %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">暂时没有任何文章。</section>
    {% endif %}

{% endblock %}

templates/blog/detail.html
{% extends "blog/base.html" %}
{% load custom_filter %}

{% block title %}
    <title>{{ article.title }} - 朱皮特</title>
{% endblock %}

{% block meta %}
    <meta name="keywords"
          content="{{ article.title }},{% for tag in article.tag.all %}{{ tag }},{% endfor %}{{ article.category }}"/>
    <meta name="description" content="{{ article.digest|safe }}"/>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="/static/css/markdown.css">
    <link rel="stylesheet" href="/static/prism/prism.css">

    <script src="/static/prism/prism.js" charset="utf-8"></script>

    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {inlineMath: [['$', '$']]},
            messageStyle: "none"
        });
    </script>

{% endblock %}

{% block content %}

    <div class="mysection content">
        <article>
            <h3 class="arc-title index-title">{{ article.title }} </h3>
            <div class="post-line bg-color">
                <ul>
                    <li><a title="{{ article.author }}发表于{{ article.date_time }}"><i class="el-time"></i>
                        <time>{{ article.date_time }}</time>
                    </a></li>
                    <li><a href="#"><i class="el-user"></i>{{ article.author }}</a></li>
                    <li><a href="#Coon" title="转到评论"><i class="el-comment"></i>{{ article.comment }}条</a></li>
                    <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}</a></li>
                </ul>
            </div>

            <!--文章正文-->
            <div class="article-content bg-color markdown-body">
                <div class="post-content" style="padding: 10px 20px 20px 10px">
                    <div class="BlogAnchor" style="text-indent: 20px; font-size: 14px; margin-bottom: 30px">
                        <p>
                            <b id="AnchorContentToggle" title="收起" style="cursor:pointer;">目录[-]</b>
                        </p>
                        <div class="AnchorContent" id="AnchorContent"></div>
                    </div>
                    {{ article.content|custom_markdown|safe }}
                </div>
            </div>
            <!--分享-->
            <div class="article-fx"><a class="fx-btn img-circle" href="javascript:;">分享</a>
                <div class="bd-fx arc-bdfx">
                    <i class="el-remove fx-close"></i>
                    <ul class="bdsharebuttonbox">
                        <li><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></li>
                        <li><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a></li>
                        <li><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a></li>
                        <li><a href="#" class="bds_tieba" data-cmd="tieba" title="分享到百度贴吧"></a></li>
                    </ul>
                    <script>window._bd_share_config = {
                        "common": {
                            "bdSnsKey": {},
                            "bdText": "",
                            "bdMini": "2",
                            "bdMiniList": false,
                            "bdPic": "",
                            "bdStyle": "1",
                            "bdSize": "32"
                        }, "share": {}
                    };
                    with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
                </div>
            </div>
            <!--END 分享-->
            <div class="cyReward " style="text-align: center">
                <div id="cyReward" role="cylabs" data-use="reward" sid="{{ source_id }}"></div>

            </div>

            <hr>


            <!--标签-->
            <div class="article_tag">
                <ul>
                    <li><a href="{% url "blog:article" pk=article.category_id %}"
                           title="归类：{{ article.category }}">{{ article.category }}</a></li>
                    {% for tag in article.tag.all %}
                        <li><a href="{% url "blog:tag" name=tag.tag_name %}"
                               title="标签：{{ tag.tag_name }} ">{{ tag.tag_name }}</a>&nbsp;</li>
                    {% endfor %}
                </ul>
            </div>

            <div class="cyEmoji" style="text-align: center">
                <div id="cyEmoji" role="cylabs" data-use="emoji" sid="{{ source_id }}"></div>
            </div>

        </article>

        <!--评论表单-->
        {% include "blog/comment.html" %}


        <script type="text/javascript" charset="utf-8" src="https://changyan.itc.cn/js/lib/jquery.js"></script>
        <script type="text/javascript" charset="utf-8"
                src="https://changyan.sohu.com/js/changyan.labs.https.js?appid=cyt6A5N47"></script>
    </div>


{% endblock %}


{% block js %}

    <script>
        function GenerateContentList() {
            $(".post-content").find("h2,h3").each(function (i, item) {
                var tag = $(item).get(0).localName;
                $(item).attr("id", "wow" + i);
                $("#AnchorContent").append('<li><a class="new' + tag + ' anchor-link"  href="#wow' + i + '">' + $(this).text() + '</a></li>');
                $(".newh2").css("margin-left", 0);
                $(".newh3").css("margin-left", 20);
                $(".newh4").css("margin-left", 40);
                $(".newh5").css("margin-left", 60);
                $(".newh6").css("margin-left", 80);
            });
            $("#AnchorContentToggle").click(function () {
                var text = $(this).html();
                if (text == "目录[-]") {
                    $(this).html("目录[+]");
                    $(this).attr({"title": "展开"});
                } else {
                    $(this).html("目录[-]");
                    $(this).attr({"title": "收起"});
                }
                $("#AnchorContent").toggle();
            });
        }
        GenerateContentList();
    </script>

{% endblock %}

templates/blog/header.html
<header class="myheader">
    <div class="top">
        <!--头像左边部分-->
        <div class="top-left">
            <div class="logo"><a href="#"><img src="/static/images/h.gif"/></a></div>
            <!--滚动消息-->
            <div class="web-xiaoxi">
                <i class="el-speaker"></i>
                <ul class="mulitline">
                    <li>正在最后的优化</li>
                    <li>完成后将放出模板</li>
                    <li>完美自适应手机</li>
                </ul>
            </div>
            <!--END 消息 -->

            <!--手机菜单按钮-->
            <div class="mobile-nav"><i class="el-lines"></i><i class="el-remove"></i></div>
        </div>
        <!--导航开始-->
        <nav class="mynav">
            <ul class="orange-text">
                <li class=""><a href="{% url "blog:index" %}">首页</a></li>
                <li><a href="{% url "blog:article" pk=0 %}">博客</a></li>
                <li class='drop'>
                    <a href="JavaScript:;">分类<i class='el-chevron-down'></i></a>
                    <div class="drop-nav orange-text ">
                        <ul>
                            {% for category in category_list %}
                                <li><a href="{% url "blog:article" pk=category.pk %}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                <li><a href="{% url "blog:archive" %}">归档</a></li>
                <li><a href="{% url "blog:link" %}">链接</a></li>
                <li><a href="{% url "blog:comment" %}">留言</a></li>
                <li><a href="{% url "blog:about" %}">关于</a></li>
            </ul>
        </nav>

        <!--这里是手机导航-->
        <div class="mob-menu">
            <!--手机顶部搜索-->
            <div class="search ">
                <form action="{% url "blog:search" %}" method="get">
                    <div class="search-index">
                        <input name="name" type="text" placeholder="请输入关键字" onfocus="this.placeholder=''"
                               onblur="this.placeholder='请输入关键字'"/>
                        <i class="el-search"><input value=" " type="submit"/></i>
                    </div>
                </form>
            </div>
            <!--手机下拉菜单-->
            <ul>
                <li><a href="{% url "blog:index" %}">首页</a></li>
                <li><a href="{% url "blog:about" %}">关于</a></li>
                <li><a href="{% url "blog:article" pk=0 %}">博客</a></li>
                <li class='mob-drop'>
                    <a href="javascrip:;">分类</a>
                    <ul class="mob-dropmenu">
                        {% for category in category_list %}
                            <li><a href="{% url "blog:article" pk=category.pk %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="{% url "blog:archive" %}">归档</a></li>
                <li><a href="{% url "blog:link" %}">职位内推</a></li>
                <li><a href="{% url "blog:comment" %}">留言</a></li>
            </ul>
        </div>
    </div>
    <!--换肤--->
    <script src="/static/js/skin.js"></script>
    <div class="select-skin">
        <div class="skin-btn">
            <a href="javascript:void(0);" class="skin-btn-open">换<br>肤</a>
        </div>

        <div class="skin-content">
            <h1>选择风格<span class="skin-close">关闭</span></h1>
            <div class="skin-content-list">
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingxin'); return false;" class="btn1">清新</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('jianyue'); return false;" class="btn2">简约</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingshuang'); return false;"
                                          class="btn3">清爽</a></div>
            </div>
        </div>
    </div>
</header>

templates/blog/right.html
<aside class="myaside">
    <!--关注我-->
    <div class="focus-me bg-color animation-div">
        <h4 class="index-title"><i class="el-heart"></i>关注我
            <small>Focus Me</small>
        </h4>
        <div class="xiangguan">

            <div><a class="benbo" href="https://github.com/jhao104/django-blog" target="_blank"><i
                    class="el-download-alt"></i></a><span>博客源码</span></div>
            <div><a class="taobao"
                    href="https://my.oschina.net/jhao104/blog"
                    target="_blank"><i class="el-blogger"></i></a><span>博客地址</span></div>
            <div><a class="side-fx"><i class="el-share-alt"></i></a><span>分享本博</span></div>
            <div><a class="mail-btn" href="javascript:;"><i class="el-envelope"></i></a><span>订阅我</span></div>
        </div>

        <div class="mail-dy">
            <form action="#">
                <input type="hidden" name="t" value="qf_booked_feedback"/>
                <input type="hidden" name="id" value="b2b151b4bc010575c083e18e227ae907aac82bc47e84d3e0"/>
                <span>订阅</span>
                <input name="to" type="text" placeholder="输入邮箱点击订阅吧" onfocus="this.placeholder=''"
                       onblur="this.placeholder='输入邮箱点击订阅吧(暂无)'"/>
                <i class="el-envelope"><input value=" " type="submit"/></i>
            </form>
            <i class="el-remove fx-close"></i>
        </div>

        <div class="bd-fx side-bdfx ">
            <i class="el-remove fx-close"></i>
            <ul class="bdsharebuttonbox">
                <li><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></li>
                <li><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a></li>
                <li><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a></li>
                <li><a href="#" class="bds_tieba" data-cmd="tieba" title="分享到百度贴吧"></a></li>
            </ul>
            <script>window._bd_share_config = {
                "common": {
                    "bdSnsKey": {},
                    "bdText": "",
                    "bdMini": "2",
                    "bdMiniList": false,
                    "bdPic": "",
                    "bdStyle": "1",
                    "bdSize": "32"
                }, "share": {}
            };
            with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
        </div>
    </div>
    <!--最新更新-->

    <div class="clos-new bg-color animation-div">
        <h4 class="index-title"><i class="el-bulb"></i>最新资讯
            <small>Latest News</small>
        </h4>
        <ul>
            <li><i class="el-cloud"></i>
                <iframe id="tianqi" scrolling="no" frameborder="0" allowtransparency="true"
                        src="http://i.tianqi.com/index.php?c=code&a=getcode&id=34&h=25&w=280"></iframe>
            </li>

            <li><i class="el-calendar"></i>历史今天：
                <iframe src="http://www.todayonhistory.com/code/6.html?w=250&h=20&bky=dotted&bks=0&fs=14&fc=#565656&hg=14&ie=0&xhx=none&sd=300&px=3&len=0&sk=1&n=0"
                        width="250" height="15" scrolling="no" frameborder="0" allowtransparency="true"></iframe>
            </li>
        </ul>
    </div>
    <!--搜索-->
    <div class="search animation-div">
        <form action="{% url "blog:search" %}" method="get">
            <div class="search-index">
                <input name="key" type="text" placeholder="请输入关键字" onfocus="this.placeholder=''"
                       onblur="this.placeholder='请输入关键字'"/>
                <i class="el-search"><input value=" " type="submit"/></i>
            </div>
        </form>
    </div>

    <!--文章排行tab-->
    <div class="mytab bg-color animation-div">
        <div class="tab-btn"><a class="hd-btn tab-active" href="javascript:;"><i class="el-comment-alt"></i>最新评论</a><a
                class="ph-btn" href="javascript:;"><i class="el-signal"></i>文章排行</a></div>
        <ul class="hudong-ul">
            <!--=======查询相册=============-->
            {% for comment in comment_list %}
                <li>
                    <div class="sd-name">
                        <span><i class="el-book"></i>{{ comment.title }}</span>
                        <a class="blue-text" href="{{ comment.url }}" title="{{ comment.comment }}">{{ comment.comment }}</a>
                        <span style="text-align: right">— &nbsp;<i class="el-user"></i>{{ comment.user_name }}</span>
                    </div>
                </li>
            {% endfor %}


        </ul>
        <!--文章排行-->
        <ul class="paihang-ul">
            {% for article in article_rank %}
                <li><span></span><a href="{% url "blog:detail" pk=article.id %}"
                                    title="{{ article.title }}">{{ article.title }}<b><i
                        class="el-eye-open"></i>({{ article.view }})</b></a></li>
            {% endfor %}
        </ul>

    </div>

    <!--标签-->
    <div class="cloud bg-color animation-div">
        <h4 class="index-title"><i class="el-tags"></i>标签云
            <small>Tags Clouds</small>
        </h4>
        <ul id="3dcloud">
            {% for tag in tag_list %}
                <li><a href="{% url "blog:tag" name=tag.tag_name %}" title="标签：{{ tag.tag_name }} ">{{ tag.tag_name }}</a></li>
            {% endfor %}
        </ul>
    </div>


    <!--友情链接-->
    {% include "blog/blogroll.html" %}
</aside>

templates/blog/search.html
{% extends "blog/base.html" %}

{% block title %}
    <title>搜索:{{ key }} - 朱皮特</title>
{% endblock %}

{% load custom_filter %}
{% block content %}
    {% paginate article_list 8 %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "blog:article" pk=0 %}"><i class="el-search"></i> 搜索到<b class="lable">{{ key }}</b>相关结果</a>
            <span class="orange-text">{{ category }}</span>
            <span style="float:right;margin-right:10px;">共:<a class="orange-text"> {{ count }} </a>条</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.view > 500 %}id="tuijian"{% elif article.view > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ article.picture }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "blog:detail" pk=article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.date_time }} 发表 "><i class="el-time"></i> {{ article.date_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>
                            <li><a href="#" title="已有 {{ article.comment }} 条评论"><i class="el-comment"></i>{{ article.comment }}</a>
                            </li>
                            <li><a title="已有 {{ article.view }} 次浏览"><i class="el-eye-open"></i>{{ article.view }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "blog:article" pk=article.category_id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>

                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1&key={{ key }}">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}&key={{ key }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}&key={{ key }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}&key={{ key }}">尾页</a></li>
            </ul>
        </div>

    </section>

{% endblock %}